name:                ImageCompressor
version:             0.1.0.0
github:              "Harmos274/ImageCompressor"
license:             BSD3
author:              "Lilian VERLHAC, Alban GAROFOLI"
maintainer:          "lilian.verlhac@epitech.eu"
copyright:           "2020 Lilian VERLHAC & Alban GAROFOLI"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Harmos274/ImageCompressor#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  imageCompressor-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -O2
    dependencies:
    - ImageCompressor

tests:
  imageCompressor-test:
    main:                MainTest.hs
    source-dirs:         test
    ghc-options:
    - -Wall
    dependencies:
    - HUnit
    - tasty
    - tasty-hunit
    - deepseq
    - ImageCompressor
